config/routes.rb
Rails.application.routes.draw do
  get 'expenses/new'

  get 'expenses/create'

  get 'expenses/edit'

  get 'expenses/update'

  get 'expenses/destroy'

  root 'home#index'

  get '/dashboard' => 'home#dashboard'

  resources :users, except: [:edit, :destroy] do
    get 'edit' => 'profiles#edit'
  end

  post 'profile' => 'profiles#update'

  resources :trips, except: :destroy do
    resources :expenses
  end

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/invite' => 'users_trips#invite'
  post '/accept' => 'users_trips#accept'
  delete '/decline' => 'users_trips#destroy'

  post 'expense/accept' => 'users_expenses#accept'
  post 'expense/pay' => 'users_expenses#pay'
  post 'expense/confirm' => 'users_expenses#confirm'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	validates :creator_id, :title,
				presence: true

	has_many :messages

	has_many :expenses

	has_many :users_trips
	has_many :users, through: :users_trips

	belongs_to :creator, class_name: "User", foreign_key: "creator_id"

	has_many :accepted_users, -> {
		where("status = ?", "accepted")
	}, through: :users_trips, source: :user

	has_many :invited_users, -> {
		where("status = ?", "invited")
	}, through: :users_trips, source: :user

	has_many :pending, -> {
		where("status = ?", "pending")
	}, class_name: "Expense"

	has_many :posted, -> {
		where("status = ?", "posted")
	}, class_name: "Expense"
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    if session[:user_id]
      @trips = User.find(session[:user_id]).trips
    else
      redirect_to login_path
    end
  end

  def show
    @trip = Trip.find(params[:id])
    users = @trip.users
    member = false
    @expense = Expense.new
    
    users.each do |user|
      if user.id == session[:user_id]
        member = true
      end
    end

    if !member
      @trip = nil
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.creator_id = session[:user_id]

    if @trip.save
      UsersTrip.create(user_id: session[:user_id], trip_id: @trip.id, status: "accepted")
      flash[:notice] = "You have successfully added a trip."
      redirect_to trip_path(@trip)
    else
      flash[:alert] = "The title cannot be blank."
      redirect_to new_trip_path
    end
  end

  def destroy
  end

  private
    def trip_params
      params.require(:trip).permit(:title, :description)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_expense_modal.html.erb
<div id="expense_modal" class="hide">
	<%= form_for [@trip, @expense], remote: true do |f| %>
		<%= f.text_field :title, placeholder: "Title" %>
		<%= f.text_area :description, placeholder: "Description" %>
		<%= f.number_field :total, placeholder: "Total", min: 0, step: 0.01 %>
		<ul>
			<% @trip.accepted_users.each do |user| %>
				<% if user.id == session[:user_id] %>
					<li>
						<%= check_box_tag "emails[]", user.profile.email, checked = true, onclick: "javascript: $(this).next().prop('disabled', !$(this).prop('checked'))" %>
						<%= user.profile.email %>
						<%= number_field_tag "amount[]", nil, disabled: false, min: 0, step: 0.01 %>
					</li>
				<% else %>
					<li>
						<%= check_box_tag "emails[]", user.profile.email, checked = false, onclick: "javascript: $(this).next().prop('disabled', !$(this).prop('checked'))" %>
						<%= user.profile.email %>
						<%= number_field_tag "amount[]", nil, disabled: true, min: 0, step: 0.01 %>
					</li>
				<% end %>
			<% end %>
		</ul>
		<%= f.submit "Add Expense" %>
	<% end %>
</div>

app/views/trips/_trip_chat.html.erb
<div id="trip_chat" class="hide">
	<div id="chat_window">
		<% @trip.messages.each do |message| %>
			<div class="message">
				<%= "(#{message.created_at.strftime('%m/%d/%Y   %I:%M%p')}) #{full_name message.user}: #{message.body}" %>
			</div>
		<% end %>
	</div>

	<div id="chat_input">
		<input id="new_message" placeholder="Enter a new message ..." />
		<input id="message_button" type="button" value="Send" />
	</div>
</div>

app/views/trips/_trip_details.html.erb
<div id="trip_details" class="hide">
	<div class="title">
		<div id="edit_trip_button">
			<% if @trip.creator_id == session[:user_id] %>
				<%= link_to "Edit", edit_trip_path(@trip) %>
			<% end %>
		</div>

		<%= @trip.title %>

		<div class="clear"></div>
	</div>

	<p>
		Description: <%= @trip.description %>
	</p>

	<h2>Members</h2>

	<%= form_tag "/invite", method: :post, remote: true, class: "add_member" do %>
		<%= email_field_tag :email, nil, placeholder: "Email" %>
		<%= hidden_field_tag :trip_id, value = @trip.id %>

		<%= submit_tag "Add Member" %>
	<% end %>

	<ol id="member_list">
		<% @trip.accepted_users.each do |user| %>
			<li>
				<%= link_to "#{user.username} | #{user.profile.email}", user_path(user) %>
			</li>
		<% end %>
	</ol>

	<h3> Waiting ...</h3>

	<ol id="invite_list">
		<% @trip.invited_users.each do |user| %>
			<li>
				<%= link_to "#{user.username} | #{user.profile.email}", user_path(user) %>
				<% if user.id == session[:user_id] %>
					<%= link_to "Accept", accept_path(trip_id: @trip.id), method: :post, remote: true, class: "accept_trip" %>
					<%= link_to "Decline", decline_path(trip_id: @trip.id), method: :delete, class: "decline_trip" %>
				<% end %>
			</li>
		<% end %>
	</ol>
</div>

app/views/trips/_trip_expenses.html.erb
<div id="trip_expenses">
	<div id="pending_expenses" class="title">
		Pending Expenses
	</div>

	<% if @trip.pending.length != 0 %>
		<% @trip.pending.each do |expense| %>
			<div class="item">
				<div class="amount">
					<%= number_to_currency(expense.total/1000.00, unit: "$") %>
				</div>

				<h3><%= expense.title %></h3>
				
				<p>
					<%= expense.description %>
				</p>

				<div class="clear"></div>
			</div>

			<div class="sub_items hide">
				<% expense.users_expenses.each do |users_expense| %>
					<div class="sub_item">
						<div class="amount">
							<%= number_to_currency(users_expense.amount/1000.00, unit: "$") %>
						</div>

						<%= full_name users_expense.user %>
					</div>
				<% end %>
			</div>
		<% end %>
	<% else %>
		<div class="item">
			There are no pending expenses.
		</div>
	<% end %>
	
	<div id="posted_expenses" class="title">
		Posted Expenses
	</div>
	<% if @trip.posted.length != 0 %>
		<% @trip.posted.each do |expense| %>
			<div class="item">
				<div class="amount">
					<%= number_to_currency(expense.total/1000.00, unit: "$") %>
				</div>

				<h3><%= expense.title %></h3>
				
				<p>
					<%= expense.description %>
				</p>

				<div class="clear"></div>
			</div>

			<div class="sub_items hide">
				<% expense.users_expenses.each do |users_expense| %>
					<div class="sub_item">
						<div class="amount">
							<%= number_to_currency(users_expense.amount/1000.00, unit: "$") %>
						</div>
						
						<%= full_name users_expense.user %>
					</div>
				<% end %>
			</div>
		<% end %>
	<% else %>
		<div class="item">
			There are no posted expenses.
		</div>
	<% end %>
</div>

app/views/trips/create.html.erb
<h1>Trips#create</h1>
<p>Find me in app/views/trips/create.html.erb</p>

app/views/trips/destroy.html.erb
<h1>Trips#destroy</h1>
<p>Find me in app/views/trips/destroy.html.erb</p>

app/views/trips/edit.html.erb
<div id="container" class="trip">
	<div id="trip_new">
		<h1>Edit Trip Details</h1>

		<%= form_for @trip do |f| %>
			<h3><%= f.text_field :title, placeholder: "Title" %></h3>
			<h3><%= f.text_area :description, placeholder: "Description" %></h3>
			
			<%= f.submit "Update Trip Details" %>
		<% end %>
	</div>
</div>

app/views/trips/index.html.erb
<div id="container" class="trip">
	<div id="trip_list">
		<div class="title">
			<div id="new_trip_button">
				<%= link_to (image_tag "/assets/add.png"), new_trip_path %>
			</div>

			Trips

			<div class="clear"></div>
		</div>

		<% @trips.each do |trip| %>
			<div class="trip_item">
				<%=link_to trip.title, trip_path(trip), remote: true, class: "trip_link" %>
			</div>
		<% end %>

		<div class="end">
			<% if @trips.length == 0 %>
				No trips are found.
			<% end %> 
		</div>
	</div>

	<div id="trip_overview">
		<div class="title">
			<div id="open_trip_button">
				<% if @trips.first %>
					<%= link_to "Open", trip_path(@trips.first) %>
				<% end %>
			</div>

			<%= @trips.first.title if @trips.first %>

			<div class="clear"></div>
		</div>

		<% if @trips.first %>
			<p>
				Description: <%= @trips.first.description %>
			</p>

			<h2>Members</h2>

			<%= form_tag "/invite", method: :post, remote: true, class: "add_member" do %>
				<%= email_field_tag :email, nil, placeholder: "Email" %>
				<%= hidden_field_tag :trip_id, value = @trips.first.id %>

				<%= submit_tag "Add Member" %>
			<% end %>

			<ol id="member_list">
				<% @trips.first.accepted_users.each do |user| %>
					<li>
						<%= link_to "#{user.username} | #{user.profile.email}", user_path(user) %>
					</li>
				<% end %>
			</ol>

			<h3> Waiting ...</h3>

			<ol id="invite_list">
				<% @trips.first.invited_users.each do |user| %>
					<li>
						<%= link_to "#{user.username} | #{user.profile.email}", user_path(user) %>
						<% if user.id == session[:user_id] %>
							<%= link_to "Accept", accept_path(trip_id: @trips.first.id), method: :post, remote: true, class: "accept_trip" %>
							<%= link_to "Decline", decline_path(trip_id: @trips.first.id), method: :delete, class: "decline_trip" %>
						<% end %>
					</li>
				<% end %>
			</ol>
		<% else %>
			<div class="end">
				No information to be displayed.
			</div>
		<% end %>
	</div>

	<div class="clear"></div>
</div>

app/views/trips/new.html.erb
<div id="container" class="trip">
	<div id="trip_new">
		<h1>New Trip</h1>

		<%= form_for @trip do |f| %>
			<h3><%= f.text_field :title, placeholder: "Title" %></h3>
			<h3><%= f.text_area :description, placeholder: "Description" %></h3>
			<%= f.submit "Add Trip" %>
		<% end %>
	</div>
</div>

app/views/trips/show.html.erb
<div id="container">
	<ul id="trip_nav">
		<li id="expenses_button" class="selected item">Expenses</li>
		<li id="chat_button" class="item">Chat</li>
		<li id="details_button" class="item">Details</li>

		<div id="add_expense_button">
			<%= link_to "Add Expense", new_trip_expense_path(trip_id: @trip.id), remote: true, id: "add_expense" %>
		</div>

		<div class="clear"></div>
	</ul>

	<% if @trip %>
		<%= render "trip_details" %>

		<%= render "trip_chat" %>

		<%= render "trip_expenses" %>

		<%= render "expense_modal" %>

	<% else %>
		<h2>You are not an administrator or a member of this trip.</h2>
	<% end %>
</div>

<%= javascript_include_tag "chat.js" %>
<%= javascript_include_tag "trip.js" %>

app/views/trips/show.js.erb
$(document).ready(function(){
	$('.trip_link').off().on('ajax:complete', function(e){
		var action = '';
		action += '<div class="title">';
			action += '<div id="open_trip_button">';
				action += '<% if @trip %>';
					action += '<%= link_to "Open", trip_path(@trip) %>';
				action += '<% end %>';
			action += '</div>';

			action += '<%= @trip.title if @trip %>';

			action += '<div class="clear"></div>';
		action += '</div>';

		action += '<% if @trip %>';
			action += '<p>';
				action += '<% description = @trip.description.gsub(/\r\n|\n|\r/,"<br>").html_safe %>';
				action += 'Description: <%= description %>';
			action += '</p>';

			action += '<h2>Members</h2>';

			action += '<%= form_tag "/invite", method: :post, remote: true, class: "add_member" do %>';
				action += '<%= email_field_tag :email, nil, placeholder: "Email" %>';
				action += '<%= hidden_field_tag :trip_id, value = @trip.id %>';

				action += ' <%= submit_tag "Add Member" %>';
			action += '<% end %>';

			action += '<ol id="member_list">';
				action += '<% @trip.accepted_users.each do |user| %>';
					action += '<li>';
						action += '<%= link_to "#{user.username} | #{user.profile.email}", user_path(user) %>';
					action += '</li>';
				action += '<% end %>';
			action += '</ol>';

			action += '<h3> Waiting ...</h3>';

			action += '<ol id="invite_list">';
				action += '<% @trip.invited_users.each do |user| %>';
					action += '<li>';
						action += '<%= link_to "#{user.username} | #{user.profile.email}", user_path(user) %>';
						action += '<% if user.id == session[:user_id] %>';
							action += ' <%= link_to "Accept", accept_path(trip_id: @trip.id), method: :post, remote: true, class: "accept_trip" %>';
							action += ' <%= link_to "Decline", decline_path(trip_id: @trip.id), method: :delete, remote: true, class: "decline_trip" %>';
						action += '<% end %>';
					action += '</li>';
				action += '<% end %>';
			action += '</ol>';
		action += '<% end %>';

		$(e.currentTarget).closest('#trip_list').siblings('#trip_overview').html(action);
	});
});

app/views/trips/update.html.erb
<h1>Trips#update</h1>
<p>Find me in app/views/trips/update.html.erb</p>