config/routes.rb
Rails.application.routes.draw do
  get 'expenses/new'

  get 'expenses/create'

  get 'expenses/edit'

  get 'expenses/update'

  get 'expenses/destroy'

  root 'home#index'

  get '/dashboard' => 'home#dashboard'

  resources :users, except: [:edit, :destroy] do
    get 'edit' => 'profiles#edit'
  end

  post 'profile' => 'profiles#update'

  resources :trips, except: :destroy do
    resources :expenses
  end

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/invite' => 'users_trips#invite'
  post '/accept' => 'users_trips#accept'
  delete '/decline' => 'users_trips#destroy'

  post 'expense/accept' => 'users_expenses#accept'
  post 'expense/pay' => 'users_expenses#pay'
  post 'expense/confirm' => 'users_expenses#confirm'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password

	before_create :encrypt_password

	validates :username,
				uniqueness: true,
				presence: true,
				length: {minimum: 3}

	validates :password,
				confirmation: true

	has_one :profile
	
	has_many :messages

	has_many :users_trips
	has_many :trips, through: :users_trips

	has_many :users_expenses
	has_many :expenses, through: :users_expenses

	has_many :own_trips, class_name: "Trip", foreign_key: "creator_id"

	has_many :own_expenses, class_name: "Expense", foreign_key: "creator_id"

	has_many :accepted_trips, -> {
		where("status = ?", "accepted")
	}, through: :users_trips, source: :trip

	has_many :invited_trips, -> {
		where("status = ?", "invited")
	}, through: :users_trips, source: :trip
	
	has_many :pending_expenses, -> {
		where("status = ?", "pending")
	}, class_name: "UsersExpense"

	has_many :unpaid_expenses, -> {
		where("status = ?", "unpaid")
	}, class_name: "UsersExpense"

	has_many :paid_expenses, -> {
		where("status = ?", "paid")
	}, class_name: "UsersExpense"
	
	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
	end

	def self.authenticate(login, password)
		for i in 0...login.length
			if login[i] == "@"
				profile = Profile.find_by(email: login)
				
				if profile
					user = profile.user
				end
			end
		end

		if !user
			user = User.find_by(username: login)
		end

		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			return user
		else
			return nil
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
    if (params[:password]).length > 5
      user = User.new(user_params)

      if user.save
        profile = Profile.new(profile_params)
        profile.user_id = user.id

        if profile.save
          session[:user_id] = user.id
          flash[:notice] = "You have successfully created a user account."
        else
          user.destroy
          flash[:alert] = "Please fill the form completely."
        end
      else
        flash[:alert] = "There was an error while creating a user account."
      end
    else
      flash[:alert] = "The password must be a minimum of 6 characters."
    end

    redirect_to root_path
  end

  private
    def user_params
      params.permit(:username, :password, :password_confirmation)
    end

    def profile_params
      params.permit(:fname, :lname, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div id="container" class="user">
	<% @users.each do |user| %>
		<% if user.id != session[:user_id] %>
			<h2><%= link_to user.username, user_path(user) %></h2>
		<% end %>
	<% end %>
</div>

app/views/users/new.html.erb
<div id="full_background">
</div>

<div id="signup_box">
	<h1>Sign up</h1>

	<%= form_tag "/signup", method: "post" do %>
		<%= text_field_tag :fname, nil,  placeholder: "First Name" %>
		<br><br>
		<%= text_field_tag :lname, nil,  placeholder: "Last Name" %>
		<br><br>
		<%= text_field_tag :username, nil,  placeholder: "Username" %>
		<br><br>
		<%= email_field_tag :email, nil, placeholder: "Email" %>
		<br><br>
		<%= password_field_tag :password, nil, placeholder: "Password" %>
		<br><br>
		<%= password_field_tag :password_confirmation, nil, placeholder: "Confirm Password" %>
		<br><br>
		<%= submit_tag "Create Account" %>
	<% end %>
</div>

app/views/users/show.html.erb
<div id="container" class="user">
	<div id="edit_button">
		<%if @user.id == session[:user_id] %>
			<%= button_to "Edit Profile", user_edit_path(@user), method: "get" %>
		<% end %>
	</div>

	<div class="clear"></div>

	<h1><%= @user.username %></h1>

	<div id="user_show">
		<div id="user_labels">
			<h3>Name: </h3>
			<h3>Email: </h3>
			<h3>Gender: </h3>
			<h3>Birthday: </h3>
			<h3>Work: </h3>
		</div>

		<div id="user_information">
			<h3><%= full_name(@user) %></h3>
			<h3><%= @user.profile.email %></h3>
			<h3><%= @user.profile.gender if @user.profile.gender%></h3>
			<h3><%= (@user.profile.birthday).strftime('%m-%d-%Y') if @user.profile.birthday%></h3>
			<h3><%= @user.profile.work if @user.profile.work %></h3>
		</div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>