config/routes.rb
Rails.application.routes.draw do
  get 'expenses/new'

  get 'expenses/create'

  get 'expenses/edit'

  get 'expenses/update'

  get 'expenses/destroy'

  root 'home#index'

  get '/dashboard' => 'home#dashboard'

  resources :users, except: [:edit, :destroy] do
    get 'edit' => 'profiles#edit'
  end

  post 'profile' => 'profiles#update'

  resources :trips, except: :destroy do
    resources :expenses
  end

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/invite' => 'users_trips#invite'
  post '/accept' => 'users_trips#accept'
  delete '/decline' => 'users_trips#destroy'

  post 'expense/accept' => 'users_expenses#accept'
  post 'expense/pay' => 'users_expenses#pay'
  post 'expense/confirm' => 'users_expenses#confirm'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if session[:user_id]
  		redirect_to dashboard_path
  	end
  end

  def dashboard
  	if session[:user_id]
  		@user = User.find(session[:user_id])
  	else
  		redirect_to root_path
  	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_invitation.html.erb
<div id="invitation">
	<% if @user.invited_trips.length != 0 %>
		<% @user.invited_trips.each do |trip| %>
			<div class="item">
				<div class="buttons">
					<%= link_to "Accept", accept_path(trip_id: trip.id), method: "post", remote: true, class: "accept_trip" %>
					<%= link_to "Decline", decline_path(trip_id: trip.id), method: "delete",remote: true, class: "decline_trip" %> 
				</div>

				<%= link_to trip.title, trip_path(trip) %>

				<div class="clear"></div>
			</div>
		<% end %>
	<% else %>
		There are no invitations for you to accept or decline.
	<% end %>
</div>

app/views/home/_paid.html.erb
<div id="paid" class="hide">
	<% if @user.paid_expenses.length != 0 %>
		<% @user.paid_expenses.each do |users_expense| %>
			<div class="item">
				<%= image_tag "/assets/add.png", class: "drop_down" %>

				<%= "You paid #{full_name(users_expense.expense.creator)} #{number_to_currency(users_expense.amount/1000.00, unit: "$")}" %>
			</div>

			<div class="sub_item hide">
				<p>
					Title: <%= users_expense.expense.title %>
				</p>

				<p>
					Description: <%= users_expense.expense.description %>
				</p>
			</div>
		<% end %>
	<% else %>
		There are no paid expenses.
	<% end %>
</div>

app/views/home/_pending.html.erb
<div id="pending" class="hide">
	<% if @user.pending_expenses.length != 0 %>
		<% @user.pending_expenses.each do |users_expense| %>
			<div class="item">
				<div class="buttons">
					<%= link_to "Accept", expense_accept_path(users_expense_id: users_expense.id), method: "post", remote: true, class: "accept_expense" %>
					<%= link_to "Reject" %>
				</div>

				<%= image_tag "/assets/add.png", class: "drop_down" %>

				<%= "You owe #{full_name(users_expense.expense.creator)} #{number_to_currency(users_expense.amount/1000.00, unit: "$")}" %> 

				<div class="clear"></div>
			</div>

			<div class="sub_item hide">
				<p>
					Title: <%= users_expense.expense.title %>
				</p>

				<p>
					Description: <%= users_expense.expense.description %>
				</p>
			</div>
		<% end %>
	<% else %>
		There are no pending expenses.
	<% end %>
</div>

app/views/home/_unpaid.html.erb
<div id="unpaid" class="hide">
	<% if @user.unpaid_expenses.length != 0 %>
		<% @user.unpaid_expenses.each do |users_expense| %>
			<% if users_expense.expense.status == "posted" %>
				<div class="item">
					<div class="buttons">
						<%= link_to "Mark as Paid", expense_pay_path(users_expense_id: users_expense.id), method: "post", remote: true, class: "pay_expense" %>
					</div>

					<%= image_tag "/assets/add.png", class: "drop_down" %>

					<%= "You owe #{full_name(users_expense.expense.creator)} #{number_to_currency(users_expense.amount/1000.00, unit: "$")}" %>

					<div class="clear"></div>
				</div>

				<div class="sub_item hide">
					<p>
						Title: <%= users_expense.expense.title %>
					</p>

					<p>
						Description: <%= users_expense.expense.description %>
					</p>
				</div>
			<% end %>
		<% end %>
	<% else %>
		There are no unpaid expenses.
	<% end %>
</div>

app/views/home/dashboard.html.erb
<div id="container" class="dashboard">
	<h1>Hi, <%= @user.profile.fname %>!</h1>

	<ul id="dashboard_nav">
		<li id="invite_button" class="selected item">Invitations</li>
		<li id="pending_button" class="item">Pending</li>
		<li id="unpaid_button" class="item">Unpaid</li>
		<li id="paid_button" class="item">Paid</li>
	</ul>

	<%= render "invitation" %>

	<%= render "pending" %>

	<%= render "unpaid" %>

	<%= render "paid" %>
</div>

<%= javascript_include_tag "dashboard" %>

app/views/home/index.html.erb
<div id="full_background">
</div>
<div id="about">
</div>